{'dataset_name': 'NCI1', 'seed': 666, 'num_workers': 1, 'cov_weight': 0, 'hyperparams': {'batch_size': 64, 'epochs': 1501, 'learning_rate': 0.0005, 'step_size': 50, 'decay_rate': 0.8}, 'architecture': {'layers': 4, 'hidden': 128, 'pooling': 'S', 'JK': 'C', 'method': 'penalty', 'dropout': 0.5, 'exps': 1, 'nonlinear': 'Sigmoid_ReLU', 'aggr': 'add', 'BN': 'Y'}, 'commit_id': 'fe658b2e3cd2ce58e21d252ab15a16540c263406', 'time_stamp': '1613735586', 'directory': '../../nlg_results/pca/board/'}
-------- FOLD0 DATASET=NCI1, COMMIT_ID=fe658b2e3cd2ce58e21d252ab15a16540c263406
Traceback (most recent call last):
  File "./main.py", line 282, in <module>
    main()
  File "./main.py", line 278, in main
    run_model(net, dataset, config=config)
  File "./main.py", line 202, in run_model
    config=config
  File "./main.py", line 113, in run_given_fold
    train_loss, train_cov = train(train_loader, model, optimizer, config)
  File "./main.py", line 67, in train
    output, cov2d = model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/space/github_private/gnnzoo/tu/model.py", line 123, in forward
    x, cov2d = conv(x, edge_index)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/space/github_private/gnnzoo/tu/conv.py", line 290, in forward
    x = self.propagate(edge_index, x=x)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 237, in propagate
    out = self.message(**msg_kwargs)
  File "/space/github_private/gnnzoo/tu/conv.py", line 306, in message
    return self.exps(torch.cat([x_i, x_j], dim=-1))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'PenaltyConv' object has no attribute 'exps'
