{'dataset_name': 'REDDIT-MULTI-12K', 'num_workers': 1, 'hyperparams': {'batch_size': 64, 'epochs': 401, 'learning_rate': 0.001, 'step_size': 10, 'decay_rate': 0.8}, 'architecture': {'layers': 3, 'hidden': 256, 'pooling': 'add', 'JK': 'last', 'nonlinear_conv': 'EB3', 'dropout': 0.5, 'variants': {'BN': 'Y'}}, 'commit_id': 'efda6ee1554ad2be9484d12192aed638dc606cb0', 'time_stamp': '1605608968', 'directory': '../../nlg_results/tu/board/'}
-------- FOLD0 DATASET=REDDIT-MULTI-12K, COMMIT_ID=efda6ee1554ad2be9484d12192aed638dc606cb0
Traceback (most recent call last):
  File "./main.py", line 260, in <module>
    main()
  File "./main.py", line 256, in main
    run_model(NLG, dataset, config=config)
  File "./main.py", line 186, in run_model
    config=config
  File "./main.py", line 101, in run_given_fold
    train_loss = train(train_loader, model, optimizer)
  File "./main.py", line 65, in train
    output = model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/model.py", line 68, in forward
    x = F.relu(self.lin1(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [64 x 256], m2: [768 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:283
