{'dataset_name': 'QM9', 'target': 1, 'model': 'NLG_R', 'seed': 777, 'hyperparams': {'batch_size': 64, 'epochs': 801, 'learning_rate': 0.0001, 'step_size': 30, 'decay_rate': 0.85}, 'architecture': {'layers': 4, 'hidden': 256, 'pooling': 'add', 'JK': 'cat', 'nonlinear_conv': 'CB', 'variants': {'BN': 'N', 'aggr_mlp': 1, 'fea_activation': 'ReLU'}}, 'commit_id': '018c113d059a3089a28d45a5889953f828391aea', 'time_stamp': '1594430267', 'directory': '../../nlg_results/dc2-Ymq2/QM9_v1/board/'}
Downloading http://www.roemisch-drei.de/qm9.tar.gz
Traceback (most recent call last):
  File "./main.py", line 62, in <module>
    dataset = QM9(path, transform=T.Compose([MyTransform(), T.Distance()]))
  File "../utils/qm9.py", line 40, in __init__
    super(QM9, self).__init__(root, transform, pre_transform, pre_filter)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 90, in __init__
    self._download()
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 142, in _download
    self.download()
  File "../utils/qm9.py", line 52, in download
    file_path = download_url(self.url, self.raw_dir)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/data/download.py", line 31, in download_url
    data = urllib.request.urlopen(url)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
