{'dataset_name': 'COLLAB', 'seed': 777, 'num_workers': 1, 'cov_weight': 0.01, 'hyperparams': {'batch_size': 32, 'epochs': 1001, 'learning_rate': 0.001, 'step_size': 50, 'decay_rate': 0.75}, 'architecture': {'layers': 4, 'hidden': 128, 'pooling': 'add', 'JK': 'cat', 'nonlinear_conv': 'penalty', 'dropout': 0.5, 'exps': 4, 'variants': {'BN': 'Y', 'aggr': 'add'}}, 'commit_id': 'b43f19535aacb936d2e2d0b0827a6153ac695358', 'time_stamp': '1612170876', 'directory': '../../nlg_results/tu/board/'}
-------- FOLD0 DATASET=COLLAB, COMMIT_ID=b43f19535aacb936d2e2d0b0827a6153ac695358
Traceback (most recent call last):
  File "./main.py", line 281, in <module>
    main()
  File "./main.py", line 277, in main
    run_model(net, dataset, config=config)
  File "./main.py", line 201, in run_model
    config=config
  File "./main.py", line 113, in run_given_fold
    train_loss, train_cov = train(train_loader, model, optimizer, config)
  File "./main.py", line 67, in train
    output, cov2d = model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/space/github_private/gnnzoo/tu/model.py", line 151, in forward
    x = self.batch_norms[i](x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 106, in forward
    exponential_average_factor, self.eps)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1923, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 512 elements not 128
