{'dataset_name': 'COLLAB', 'seed': 777, 'num_workers': 2, 'cov_weight': 0.001, 'hyperparams': {'batch_size': 32, 'epochs': 1001, 'learning_rate': 0.001, 'step_size': 50, 'decay_rate': 0.75}, 'architecture': {'layers': 4, 'hidden': 256, 'pooling': 'add', 'JK': 'cat', 'nonlinear_conv': 'penalty', 'dropout': 0.5, 'variants': {'BN': 'Y', 'aggr': 'add'}}, 'commit_id': 'dfedd416762fab1c140a4e5af58483ea41088ef5', 'time_stamp': '1612161557', 'directory': '../../nlg_results/tu/board/'}
-------- FOLD0 DATASET=COLLAB, COMMIT_ID=dfedd416762fab1c140a4e5af58483ea41088ef5
Traceback (most recent call last):
  File "./main.py", line 281, in <module>
    main()
  File "./main.py", line 277, in main
    run_model(net, dataset, config=config)
  File "./main.py", line 201, in run_model
    config=config
  File "./main.py", line 113, in run_given_fold
    train_loss, train_cov = train(train_loader, model, optimizer, config)
  File "./main.py", line 67, in train
    output, cov2d = model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/space/github_private/gnnzoo/tu/model.py", line 147, in forward
    x = F.relu(self.lin3(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [32 x 65536], m2: [1024 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:283
